kitao/pyxel

README.md
Update command for install "glfw" on debian systems.
=> fix debian commands

pyxel/app.py
Added another fallback in case user changes desktop folder name.
=> Solution to Issue #11

README.md
Not sure if I already have other dependencies, but this works for me in fedora 28
=> Fedora instructions

README.fr.md
=> Translate README in French

Pipfile, requirements.txt
This is just a small addition to add an easy way to install dependencies for development on Pyxel.
Pipenv (Pipfile)
```
pipenv install
```
Virtualenv (requirements.txt)
```
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
```
Information about pipenv: [en](https://pipenv.readthedocs.io/en/latest/), [ja](https://pipenv-ja.readthedocs.io/ja/translate-ja/).
=> Add requirements and Pipfile

README.md
I've provided a sample of the How To Contribute section tailored for this project
=> Add "How To Contribute" Section in the README.md #16

README.md
=> Found small typo

pyxel/editor/editor.py
Now you can change selected color by pressing number buttons.
=> Add more key shortcut for PyxelEditor

pyxel/packager.py
=> Fix assets packaging on python package case

README.ko.md
The existing translation was modified to make the sentence more natural.
Issue #199
=> README.ko.md: Triangle Drawing API

README.ko.md
=> README.ko.md: Triangle Drawing API Usage

README.es.md
- Add triangle example
- Complete definition of `init` parameters
=> Add new translation in examples and API

README.es.md
Add Spanish translation for `tri` and `trib` functions
=> Add missing translations

README.es.md
=> Fixes on spanish

README.ko.md
=> Update Korean translation

README.es.md
=> Add ES translation of pget() and pset()

README.ko.md
=> Add translation of pget(), pset()

pyxel/core/src/pyxelcore/audio.cc, pyxel/core/src/pyxelcore/window.cc
invalide -> invalid
boader -> border
=> Fix error message typos

README.cn.md, README.es.md, README.ja.md, README.ko.md, README.md, README.pt.md
=> Add portuguese translation

README.pt.md
Updates the translation mentioned on #199
=> Update translation pt

README.es.md
=> Update translation es

README.cn.md, README.es.md, README.it.md, README.ja.md, README.ko.md, README.md, README.pt.md
I translated the README to italian
=> Italian translation of readme

README.cn.md, README.de.md, README.es.md, README.fr.md, README.it.md, README.ja.md, README.ko.md, README.md, README.pt.md, README.ru.md
=> German readme

README.de.md
Updated the german README for version 1.5.0
=> German readme 1.5.0

README.ko.md
=> Update korean translation for version 1.5.0

pyxel/__init__.pyi
=> Make optional arguments None by default

doc/README.pt.md
=> Update portuguese translation

doc/README.fr.md
answering request from kitao#332 + a few minor changes in the same line
=> Update french readme for new init param

doc/README.pt.md
=> Update init translation (pt)

doc/README.es.md
=> Update the spanish translation

doc/README.es.md
=> Fix missing translations to Spanish

doc/README.fr.md
Translated a new method and took the opportunity to go over some existing things.
@grewn0uille would like your review here!
=> Revise French docs

doc/README.ko.md
=> Update korean translation for version 1.6.0

doc/README.it.md
Hi, I completed the README translation for the issue #366.
Hope it helps!
=> Update README's Italian translation

doc/README.es.md
Due to https://github.com/kitao/pyxel/issues/370#issuecomment-1021238808. I checked carefully, and fixed these translation issues:
- Some things should not be translated.
- Some translations are not wrong, but a little confusing or vague.
- Some translations are wrong.
=> Fix some spanish translations

python/pyxel/examples/13_bitmap_font.py
Added calculation of offset values.
Changed the drawing position of the next glyph.
Added spacing argument to draw_text().
=> Change glyph drawing position

docs/README.cn.md
Fixed an untranslated paragraph and translated some open-source terms into more suitable expressions.
=> Fixed a description in the Chinese document

python/pyxel/utils.py
#521 
Fixed the issue of gbk encoding format compatibility and drive path on Windows when app2exe was executed
=> Fixed the issue of gbk encoding format compatibility and drive path on Windows when app2exe was executed

docs/README.tr.md
Add Turkish Language support for README.md 
Releated: #550
=> Add Turkish Language support for README.md
