pyxel/app.py

Changed line 122 on app.py from self.module._frame_count to self._module.frame_count
That would cause AttributeError: module "pyxel" has no attribute "_frame_count" when you tried to use the btnr function.

Change on Btnr - Solving AttributeError

---

README.md

* [python-glfw](https://www.archlinux.org/packages/community/any/python-glfw/) has been fixed and moved to [community].
* [python-pyxel](https://aur.archlinux.org/packages/python-pyxel/) is now in place in AUR.
It will take a few minutes until the AUR system detects that python-glfw is now in [community].

Update installation instructions for Arch

---

pyxel/app.py

This should help the problem described in #7. This is just a simple trick that only works with PNGs.
There are still other ways to achieve this, but the only other methods I know are probably going to impact a lot on the final quality.

Hint to reduce the size of the captured GIF

---

pyxel/app.py

This is a small fix to address #94, changing `self._key_state[key]` to `self._key_state.get(key)`

Prevent crash caused by 'fn' keypress on macOS

---

pyxel/app.py

Fixes Pyxel crashing with the following error:
```
Traceback (most recent call last):
File ".\06_click_game.py", line 130, in <module>
App()
File ".\06_click_game.py", line 58, in __init__
pyxel.run(self.update, self.draw)
File "D:\Dropbox\code\pyxel\pyxel\app.py", line 252, in run
main_loop()
File "D:\Dropbox\code\pyxel\pyxel\app.py", line 244, in main_loop
self._update_frame()
File "D:\Dropbox\code\pyxel\pyxel\app.py", line 419, in _update_frame
self._update_mouse_pos()
File "D:\Dropbox\code\pyxel\pyxel\app.py", line 434, in _update_mouse_pos
pyxel.mouse_x = int((x - self._viewport_left) / self._viewport_scale)
ZeroDivisionError: float division by zero
```
Steps to reproduce (on Windows 10):
1. Start any game, for instance `01_hello_pyxel.py` or `06_click_game.py` from examples
1. …

Fix crash on minimize

---

pyxel/app.py

This is a simple fix for #99
I tested it with a simple app and verified that it no longer crashes when I enter fullscreen mode, and the functionality of everything else appears to be the same.  I am well outside my comfort zone when it comes to working with game engines, so please let me know if there's any way I can make this fix more robust.

Set non-zero refresh rate for glfw.set_window_monitor calls

---

pyxel/__init__.py

To set colors with a word.
Almost all names of colors are the same with ones of  `matplotlib`.
You can use this class like ,
```
from pyxel import Color
pyxel.rect(x=10, y=10, w=20, h=20, col=Color.YELLOW)
```

Add Color class

---

pyxel/packager.py

- Use argparse native python lib to handle the parameters
- Add icon support through `-i` or `--icon` option

Use argparse on packager and add icon option

---

pyxel/packager.py

The following error occurs when running the pyxelpackager:
```
Traceback (most recent call last):
File "c:\users\liri\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\users\liri\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\Liri\AppData\Local\Programs\Python\Python37\Scripts\pyxelpackager.exe\__main__.py", line 9, in <module>
File "c:\users\liri\appdata\local\programs\python\python37\lib\site-packages\pyxel\packager.py", line 28, in run
dirname = os.path.dirname(args.entrypoint.name) or "."
AttributeError: 'Namespace' object has no attribute 'entrypoint'
```
This is because the argument was renamed from `entrypoint` to `python_file` in a recent commit. …

Fix errors that occur when run pyxelpackager

---

README.cn.md
README.ja.md
README.ko.md
README.md

`sudo pip3 install -U pyxel`とするとpipが
> If executing pip with sudo, you may want sudo's -H flag.
と警告してくるので(必須ではないけど)sudoに`-H`オプションをつけたほうがよろしいかと。
When run `sudo pip3 install -U pyxel`, pip will warn
> If executing pip with sudo, you may want sudo's -H flag.
(although it is not required), I think it's better to add the `-H` option to sudo.
Translated from Japanese to English by Google Translate.

Change from sudo pip3 to sudo -H pip3

---

pyxel/core/src/pyxelcore.cc

This PR fixes a segmentation fault error when executing various pyxel functions when the engine is not initialized. Now, most functions force initialization and some functions just return reasonable default values.
I haven't sorted out all details, and I am not sure if we should force initialization or raise a Python exception. Tell me if this approach is sane. There are a few places that we could enforce a different default behavior other than forcing initialization or raising exceptions (e.g. drawing functions could be no-op). But I am not sure how do you want to handle this.

Protect access to system pointer when pyxel is not yet initialized

---

pyxel/__init__.py

Since Python 3.3 using base classes straight from collections instead of collections.abc is deprecated ([source](https://docs.python.org/3/whatsnew/3.3.html#collections)) and will stop working in Python 3.10
This is a quick edit to fix that

Update __init__.py to fix deprecation warning

---

pyxel/cli.py

When exiting after playing pyxapp, an error occurs that the temporary directory cannot be deleted.
It seemed that the temporary directory could not be deleted without terminating the process, so I decided to run it in a sub-process.

Fix PermissionError to delete tempdirectory

---

crates/pyxel-engine/src/system.rs

The current loop has lots of `unsafe`s and "lifetime" issues.
By using `emscripten_set_main_loop_arg`, we do not need to use `thread_local` or `transmute`.
It compiles and runs the same as before, including `Error: unwind`.
However, it needs to be reviewed and checked in other environments.

Make emscripten loop clean

---

wasm/pyxel.js

Current `pyxel.js` misuses `oncontextmenu` properties, so it won't block the context menu. 
The value of `oncontextmenu` should be the reference of a function.
This PR resolves the issue.

Fix the contextmenu issue.

---

crates/pyxel-core/Cargo.toml
crates/pyxel-core/src/audio.rs
crates/pyxel-core/src/graphics.rs
crates/pyxel-core/src/image.rs

Using `array-macro` isn't really necessary here now that standard library has `array::from_fn`. This makes the codebase somewhat safer as `std` has more people looking into its safety than `array-macro` crate (which pretty much is maintained by just me).

Remove array-macro dependency

---

python/pyxel/cli.py

When `app2exe` are executed, **startup_script_file** is generated and the running pyxapp file name is written.The constant **APP_FILE_EXTENSION** is called here as the file extension (**.pyxapp**), but there is an extra dot symbol, which will result in a file name like xxx`..`pyxapp, causing the exe file fails to be run,because the corresponding filename file could not be found.
The same reference error when executing `app2html`, but running the html will generate the corresponding filename file through the **_copyFileFromBase64** method in **pyxel.js**, although there will be no runtime error, it is better to modify together.
Current versions greater than 2.0.10 have the above problem.

APP_FILE_EXTENSION constant reference error

---

python/pyxel/cli.py

When getting metadata in startup_script_file, specify utf8 encoding to be compatible with other characters such as Chinese

get metadata in utf8

---

python/pyproject.toml

The config references the directory it's in, so we can just omit it.

Removed python-source value to work around issue in maturin 1.7.1+

---

rust/pyxel-engine/src/canvas.rs
rust/pyxel-engine/src/sound.rs

filling a large area (such as the entire screen starting from one of the corner pixels) can result in very deeply nested recursion in `fill_rec`, manifesting as a crash when calling `fill(...)` from python.
my approach to fixing this is to use a stack of coordinates to visit in a loop rather than recursing. this stack is initialised with a worst-case capacity of every pixel in the clipping region to avoid reallocs.
i've added a test that does a worst-case fill on a large canvas to validate the solution.
unrelated: while working on this i noticed that `test_sound_set` was failing. the `sound` instance in the test was missing the last two volumes & effects that were being asserted, so i added them to the `.set(...)` call. that change is in a separate commit from the `fill_rec` fix.
let me …

fix: stack overflow in `fill`
